### ISSUE TITLE
rowCount not always accurate

### ISSUE THREAD

**Issue by kdszafranski** [LukeSchlangen/nodeFire#13]
SQL branch: Some students have noticed that in the check for a user (via result.rowCount === 0) is not always accurate. [According to this issue, ](https://github.com/brianc/node-postgres/issues/979,) it is not interchangeable with rows.length and signifies rows affected, not necessarily rows received. Recommend changing this to rows.length == 0.

**Comment by LukeSchlangen** [comment]
Thank you!
