### ISSUE TITLE
README.md Improvements

### ISSUE THREAD

**Issue by LukeSchlangen** [LukeSchlangen/nodeFire#4]
Need someone completely unfamiliar with the project to walk through the README and suggest improvements based on any confusion they run into.

**Comment by zakaye** [comment]
I'll take a look :>

**Comment by zakaye** [comment]
It's pretty clear to me, I feel like the only way to improve on it is to take screenshots.
One tiny thing is at the bottom "Toggle google to on" where as the toggle is called "enable"

**Comment by zakaye** [comment]
Just to add on, I have not heard of Firebase before but can follow just fine :>

**Comment by hillaryfraley** [comment]
Fellow unfamiliar reader here :) I took a look and came up with a few ideas. Sent a pull request, I hope it helps!

**Comment by LukeSchlangen** [comment]
Thank you @zakaye ! @hillaryfraley those are perfect. Thank you!

**Comment by zakaye** [comment]
I tried adding screenshots, doesn't look as nice as I wanted it to be, I think this is better without.

**Comment by salman-bhai** [comment]
@LukeSchlangen is this issue closed? I could take a look if you want.
